### ISSUE TITLE
Some items being ignore due to hardcoded limits

### ISSUE THREAD

**Issue by dsl101** [ndaidong/feed-reader#3]
Can I ask what the purpose behind the length checks at the beginning of `normalize()` are? Specifically this:

```
  if (!link || !title ||
    !isString(link) || !isString(title) ||
→   link.length < 10 || title.length < 10) {
    return false;
  }
```
It's taken me ages to track down why some items in a feed are returning as `undefined`, and it's because the title was short.

**Comment by ndaidong** [comment]
I have a service that uses this package to parse content for some websites ([TechPush](http://techpush.xyz/), [FOMO](http://fomo.link/), etc). When I get an article with title < 10 letters, if there is no error, that article itself is often not interesting to readers. 
Related: #1

**Comment by dsl101** [comment]
Ah yes - I didn't spot #1 but I really think that should be under control of the application not the library...
