### ISSUE TITLE
remove xml response content-type check ?

### ISSUE THREAD

**Issue by eviltik** [ndaidong/feed-reader#39]
Some response don't have content-type, see this one

https://www.hackerone.com/blog.rss

I've commented the content-type check in your code, and it's working, but ... i don't know ... perhaps you would prefer to pass an option to enable/disable content-type check ?

What do you think ?

**Comment by ndaidong** [comment]
@eviltik yes, you're right. We can add something like `{acceptContentTypes: [a, b, c] }`

**Comment by eviltik** [comment]
https://github.com/ndaidong/feed-reader/pull/40

**Comment by ndaidong** [comment]
@eviltik I just recheck RSS from hackerone, it returns `application/rss+xml; charset=utf-8`, that should pass our condition because it contains 'xml'. Actually it works for me without any change.

**Comment by ndaidong** [comment]
however we can remove check here, if it isn't valid xml, the error will be found by validator.

**Comment by eviltik** [comment]
Agree with you. Another idea should be to have a "skipContentTypeCheck" ?
