### ISSUE TITLE
Support optional item elements in parsed RSS 2.0 items

### ISSUE THREAD

**Issue by 3ventic** [ndaidong/feed-reader#51]
I love the simplicity of this library, but it drops the optional elements on items, such as enclosure and author, leaving no way to access them. Could support for those be added?

**Comment by ndaidong** [comment]
@3ventic thank you for your suggestion. I'm considering to add some new features to this lib while still keeping the api simple as much as possible. Maybe in the next version, we will get full content and the media elements.

**Comment by ndaidong** [comment]
@3ventic hello, if you have freet time, please check these new [options](https://github.com/ndaidong/feed-reader#options-optional) to see if that's what you need. Feel free to reopen this issue if any problem. Thank you.
