### ISSUE TITLE
[Feature Request] need more fields, want the result can be customized via options

### ISSUE THREAD

**Issue by sarike** [ndaidong/feed-reader#56]
I use this tool to parse rss feed, but there are some fields I need not in the result, such as `image`, `owner`.

I want two options  `extraFeedFields` and `extraEntryFields` used as function, their return value will be merged into the feed and entry fields. So everyone can custom the result.

```js
const feedData = await read('https://some-rss-feed-xml/', {
    extraFeedFields: (channel) {
       return {
          image: channel['itunes:image'],
          owner: channel['iutnes:owner']
      }
   },
})
```
result: 
```json
{
  "title": "xxx",
  "link": "xxx",
  "description": "xxx",
  "language": "",
  "generator": "",
  "published": "",
  "entries": [...],
  "image": {...},
  "owner": {...},
}
```

**Comment by ndaidong** [comment]
@sarike yes, that's smart idea, thank you. I see you forked this repo, are you making a PR for that?

**Comment by sarike** [comment]
ok, I will have a try.

**Comment by ndaidong** [comment]
@sarike thank you, I've merge your pr and release [v6.1.2](https://github.com/ndaidong/feed-reader/releases/tag/v6.1.2)

FYI, I renamed `extraFeedFields` to `getExtraFeedFields` and `extraEntryFields` to `getExtraEntryFields`.

**Comment by sarike** [comment]
ok
